import Cta from "@/components/Cta";
import Finish from "@/components/Finish";
import Gnb from "@/components/Gnb";
import type { Metadata } from "next";
import "./global.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body>
        <Gnb />
        <Cta />
        <main>{children}</main>
        <Finish />
      </body>
    </html>
  );
}
