import Cta from "@/components/Cta";
import Finish from "@/components/Finish";
import Gnb from "@/components/Gnb/Gnb";
import ProgressBar from "@/components/Progressbar";
import { Metadata } from "next";
import "./global.css";

export const metadata: Metadata = {
  title: "Inhye's Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body>
        <Gnb />
        <ProgressBar />
        <Cta />
        <main>{children}</main>
        <div id="modal-root"></div>
        <Finish />
      </body>
    </html>
  );
}
